apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraiscan-frontend
  labels:
    app: oraiscan-frontend
spec:
  selector:
    matchLabels:
      app: oraiscan-frontend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: oraiscan-frontend
    spec:
      containers:
      - name: oraiscan-frontend
        image: thao1996/oraiscan-frontend:98234d646c07ae37436c573db28f5d4634cf9461
        env:
        - name: "REACT_APP_SITE_TITLE"
          value: "Oraiscan - Oraichain explorer"
        - name: "REACT_APP_SITE_DESC"
          value: "AI-Powered Data Oracle"
        - name: "REACT_APP_SITE_KEYWORDS"
          value: "Oraichain, Oraiscan, AI Oracle"
        - name: "REACT_APP_SITE_URL"
          value: "https://scan.orai.io"
        - name: "REACT_APP_SITE_TITLE_FOR_SHARE"
          value: "Oraiscan - Oraichain explorer "
        - name: "REACT_APP_API_DEV"
          value: "https://api.scan.orai.io/v1"
        - name: "REACT_APP_API_PROD"
          value: "https://api.scan.orai.io/v1"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
